name: Example
on: [push]

jobs:
  my_job:
    runs-on: ubuntu-latest

    steps:
    - name: Mask fruit
#      uses: simar7/golang-github-action@main
#      uses: docker://simar7/golang-github-action:latest
      uses: docker://simar7/golang-github-action:lite
      with:
        fruit: banana

    - name: Echo fruit
      run: echo "apple, banana, and orange"